FROM node:16

RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client

RUN apt-get update && apt-get install

COPY . /usr/src/client/
RUN yarn

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV CHOKIDAR_USEPOLLING=true

CMD [ "yarn", "dev" ]
