
FROM node:16

WORKDIR /client

RUN apt-get update && apt-get install

COPY package*.json ./
RUN yarn install && yarn global add create-nuxt-app

COPY shell/*.sh ./shell/
RUN . shell/create-dotenv.sh
RUN ls -la

COPY . ./
RUN yarn build
COPY .nuxt /.nuxt/
