version: "3.8"

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.local
    command: yarn dev
    volumes:
      - ./client:/usr/src/client
      - client_node_modules:/usr/src/client/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env.develop
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    tty: true

  api:
    build:
      context: api
      dockerfile: Dockerfile.local
    command: yarn start:dev
    volumes:
      - api_node_modules:/usr/src/api/node_modules
    ports:
      - 4000:4000
    env_file:
      - .env.develop
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  client_node_modules:
  api_node_modules:
  postgres:
