version: "3.8"

services:
  client:
    build:
      context: client
      dockerfile: Docker/Dockerfile
    ports:
      - 3000:3000
    command: yarn dev
    working_dir: /client
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
