version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: yarn dev
    volumes:
      - node_modules:/usr/src/node_modules
    ports:
      - 3000:3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    tty: true
volumes:
  node_modules:
