version: "3.8"

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.local
    command: sh -c "yarn && yarn dev"
    working_dir: "/client"
    volumes:
      - ./client:/client
      - node_modules:/src/client/node_modules
    ports:
      - 3000:3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    tty: true
volumes:
  node_modules:
