#!/bin/sh -l

set -e

echo "CTF_SPACE_ID=$CTF_SPACE_ID" >> .env
echo "CTF_CDA_ACCESS_TOKEN=$CTF_CDA_ACCESS_TOKEN" >> .env
echo "CTF_BLOG_POST_TYPE_ID=$CTF_BLOG_POST_TYPE_ID" >> .env
echo "VUE_APP_FIREBASE_API_KEY=$VUE_APP_FIREBASE_API_KEY" >> .env
echo "VUE_APP_FIREBASE_AUTH_DOMAIN=$VUE_APP_FIREBASE_AUTH_DOMAIN" >> .env
echo "VUE_APP_FIREBASE_DATABASE_URL=$VUE_APP_FIREBASE_DATABASE_URL" >> .env
echo "VUE_APP_FIREBASE_PROJECT_ID=$VUE_APP_FIREBASE_PROJECT_ID" >> .env
echo "VUE_APP_FIREBASE_STORAGE_BUCKET=$VUE_APP_FIREBASE_STORAGE_BUCKET" >> .env
echo "VUE_APP_FIREBASE_MESSAGING_SENDER_ID=$VUE_APP_FIREBASE_MESSAGING_SENDER_ID" >> .env
echo "VUE_APP_FIREBASE_APP_ID=$VUE_APP_FIREBASE_APP_ID" >> .env
echo "VUE_APP_FIREBASE_MEASUREMENT_ID=$VUE_APP_FIREBASE_MEASUREMENT_ID" >> .env
echo "DUMMY_APP_ID=$DUMMY_APP_ID" >> .env
