FROM node:16

RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api

RUN apt-get update && apt-get install

COPY . /usr/src/api/
# FIXME: yarn buildが動かないので、現状yarn buildしてからdocker-compose buildしないといけない
RUN yarn && yarn build
